export interface PokeTypeCompatibilityInterface {
    defTypeId: number;
    atkTypeId: number;
    damageRate: number;
}

export default function pokeTypeCompatibility(): PokeTypeCompatibilityInterface[] {
    return [
        {defTypeId:1 , atkTypeId:1 , damageRate:1  },
        {defTypeId:1 , atkTypeId:2 , damageRate:1  },
        {defTypeId:1 , atkTypeId:3 , damageRate:1  },
        {defTypeId:1 , atkTypeId:4 , damageRate:1  },
        {defTypeId:1 , atkTypeId:5 , damageRate:1  },
        {defTypeId:1 , atkTypeId:6 , damageRate:1  },
        {defTypeId:1 , atkTypeId:7 , damageRate:2  },
        {defTypeId:1 , atkTypeId:8 , damageRate:1  },
        {defTypeId:1 , atkTypeId:9 , damageRate:1  },
        {defTypeId:1 , atkTypeId:10, damageRate:1  },
        {defTypeId:1 , atkTypeId:11, damageRate:1  },
        {defTypeId:1 , atkTypeId:12, damageRate:1  },
        {defTypeId:1 , atkTypeId:13, damageRate:1  },
        {defTypeId:1 , atkTypeId:14, damageRate:0  },
        {defTypeId:1 , atkTypeId:15, damageRate:1  },
        {defTypeId:1 , atkTypeId:16, damageRate:1  },
        {defTypeId:1 , atkTypeId:17, damageRate:1  },
        {defTypeId:1 , atkTypeId:18, damageRate:1  },
        {defTypeId:2 , atkTypeId:1 , damageRate:1  },
        {defTypeId:2 , atkTypeId:2 , damageRate:0.5},
        {defTypeId:2 , atkTypeId:3 , damageRate:2  },
        {defTypeId:2 , atkTypeId:4 , damageRate:1  },
        {defTypeId:2 , atkTypeId:5 , damageRate:0.5},
        {defTypeId:2 , atkTypeId:6 , damageRate:0.5},
        {defTypeId:2 , atkTypeId:7 , damageRate:1  },
        {defTypeId:2 , atkTypeId:8 , damageRate:1  },
        {defTypeId:2 , atkTypeId:9 , damageRate:2  },
        {defTypeId:2 , atkTypeId:10, damageRate:1  },
        {defTypeId:2 , atkTypeId:11, damageRate:1  },
        {defTypeId:2 , atkTypeId:12, damageRate:0.5},
        {defTypeId:2 , atkTypeId:13, damageRate:2  },
        {defTypeId:2 , atkTypeId:14, damageRate:1  },
        {defTypeId:2 , atkTypeId:15, damageRate:1  },
        {defTypeId:2 , atkTypeId:16, damageRate:1  },
        {defTypeId:2 , atkTypeId:17, damageRate:0.5},
        {defTypeId:2 , atkTypeId:18, damageRate:0.5},
        {defTypeId:3 , atkTypeId:1 , damageRate:1  },
        {defTypeId:3 , atkTypeId:2 , damageRate:0.5},
        {defTypeId:3 , atkTypeId:3 , damageRate:0.5},
        {defTypeId:3 , atkTypeId:4 , damageRate:2  },
        {defTypeId:3 , atkTypeId:5 , damageRate:2  },
        {defTypeId:3 , atkTypeId:6 , damageRate:0.5},
        {defTypeId:3 , atkTypeId:7 , damageRate:1  },
        {defTypeId:3 , atkTypeId:8 , damageRate:1  },
        {defTypeId:3 , atkTypeId:9 , damageRate:1  },
        {defTypeId:3 , atkTypeId:10, damageRate:1  },
        {defTypeId:3 , atkTypeId:11, damageRate:1  },
        {defTypeId:3 , atkTypeId:12, damageRate:1  },
        {defTypeId:3 , atkTypeId:13, damageRate:1  },
        {defTypeId:3 , atkTypeId:14, damageRate:1  },
        {defTypeId:3 , atkTypeId:15, damageRate:1  },
        {defTypeId:3 , atkTypeId:16, damageRate:1  },
        {defTypeId:3 , atkTypeId:17, damageRate:0.5},
        {defTypeId:3 , atkTypeId:18, damageRate:1  },
        {defTypeId:4 , atkTypeId:1 , damageRate:1  },
        {defTypeId:4 , atkTypeId:2 , damageRate:1  },
        {defTypeId:4 , atkTypeId:3 , damageRate:1  },
        {defTypeId:4 , atkTypeId:4 , damageRate:0.5},
        {defTypeId:4 , atkTypeId:5 , damageRate:1  },
        {defTypeId:4 , atkTypeId:6 , damageRate:1  },
        {defTypeId:4 , atkTypeId:7 , damageRate:1  },
        {defTypeId:4 , atkTypeId:8 , damageRate:1  },
        {defTypeId:4 , atkTypeId:9 , damageRate:2  },
        {defTypeId:4 , atkTypeId:10, damageRate:0.5},
        {defTypeId:4 , atkTypeId:11, damageRate:1  },
        {defTypeId:4 , atkTypeId:12, damageRate:1  },
        {defTypeId:4 , atkTypeId:13, damageRate:1  },
        {defTypeId:4 , atkTypeId:14, damageRate:1  },
        {defTypeId:4 , atkTypeId:15, damageRate:1  },
        {defTypeId:4 , atkTypeId:16, damageRate:1  },
        {defTypeId:4 , atkTypeId:17, damageRate:0.5},
        {defTypeId:4 , atkTypeId:18, damageRate:1  },
        {defTypeId:5 , atkTypeId:1 , damageRate:1  },
        {defTypeId:5 , atkTypeId:2 , damageRate:2  },
        {defTypeId:5 , atkTypeId:3 , damageRate:0.5},
        {defTypeId:5 , atkTypeId:4 , damageRate:0.5},
        {defTypeId:5 , atkTypeId:5 , damageRate:0.5},
        {defTypeId:5 , atkTypeId:6 , damageRate:2  },
        {defTypeId:5 , atkTypeId:7 , damageRate:1  },
        {defTypeId:5 , atkTypeId:8 , damageRate:2  },
        {defTypeId:5 , atkTypeId:9 , damageRate:0.5},
        {defTypeId:5 , atkTypeId:10, damageRate:2  },
        {defTypeId:5 , atkTypeId:11, damageRate:1  },
        {defTypeId:5 , atkTypeId:12, damageRate:2  },
        {defTypeId:5 , atkTypeId:13, damageRate:1  },
        {defTypeId:5 , atkTypeId:14, damageRate:1  },
        {defTypeId:5 , atkTypeId:15, damageRate:1  },
        {defTypeId:5 , atkTypeId:16, damageRate:1  },
        {defTypeId:5 , atkTypeId:17, damageRate:1  },
        {defTypeId:5 , atkTypeId:18, damageRate:1  },
        {defTypeId:6 , atkTypeId:1 , damageRate:1  },
        {defTypeId:6 , atkTypeId:2 , damageRate:2  },
        {defTypeId:6 , atkTypeId:3 , damageRate:1  },
        {defTypeId:6 , atkTypeId:4 , damageRate:1  },
        {defTypeId:6 , atkTypeId:5 , damageRate:1  },
        {defTypeId:6 , atkTypeId:6 , damageRate:0.5},
        {defTypeId:6 , atkTypeId:7 , damageRate:2  },
        {defTypeId:6 , atkTypeId:8 , damageRate:1  },
        {defTypeId:6 , atkTypeId:9 , damageRate:1  },
        {defTypeId:6 , atkTypeId:10, damageRate:1  },
        {defTypeId:6 , atkTypeId:11, damageRate:1  },
        {defTypeId:6 , atkTypeId:12, damageRate:1  },
        {defTypeId:6 , atkTypeId:13, damageRate:2  },
        {defTypeId:6 , atkTypeId:14, damageRate:1  },
        {defTypeId:6 , atkTypeId:15, damageRate:1  },
        {defTypeId:6 , atkTypeId:16, damageRate:1  },
        {defTypeId:6 , atkTypeId:17, damageRate:2  },
        {defTypeId:6 , atkTypeId:18, damageRate:1  },
        {defTypeId:7 , atkTypeId:1 , damageRate:1  },
        {defTypeId:7 , atkTypeId:2 , damageRate:1  },
        {defTypeId:7 , atkTypeId:3 , damageRate:1  },
        {defTypeId:7 , atkTypeId:4 , damageRate:1  },
        {defTypeId:7 , atkTypeId:5 , damageRate:1  },
        {defTypeId:7 , atkTypeId:6 , damageRate:1  },
        {defTypeId:7 , atkTypeId:7 , damageRate:1  },
        {defTypeId:7 , atkTypeId:8 , damageRate:1  },
        {defTypeId:7 , atkTypeId:9 , damageRate:1  },
        {defTypeId:7 , atkTypeId:10, damageRate:2  },
        {defTypeId:7 , atkTypeId:11, damageRate:2  },
        {defTypeId:7 , atkTypeId:12, damageRate:0.5},
        {defTypeId:7 , atkTypeId:13, damageRate:0.5},
        {defTypeId:7 , atkTypeId:14, damageRate:1  },
        {defTypeId:7 , atkTypeId:15, damageRate:1  },
        {defTypeId:7 , atkTypeId:16, damageRate:0.5},
        {defTypeId:7 , atkTypeId:17, damageRate:1  },
        {defTypeId:7 , atkTypeId:18, damageRate:2  },
        {defTypeId:8 , atkTypeId:1 , damageRate:1  },
        {defTypeId:8 , atkTypeId:2 , damageRate:1  },
        {defTypeId:8 , atkTypeId:3 , damageRate:1  },
        {defTypeId:8 , atkTypeId:4 , damageRate:1  },
        {defTypeId:8 , atkTypeId:5 , damageRate:0.5},
        {defTypeId:8 , atkTypeId:6 , damageRate:1  },
        {defTypeId:8 , atkTypeId:7 , damageRate:0.5},
        {defTypeId:8 , atkTypeId:8 , damageRate:0.5},
        {defTypeId:8 , atkTypeId:9 , damageRate:2  },
        {defTypeId:8 , atkTypeId:10, damageRate:1  },
        {defTypeId:8 , atkTypeId:11, damageRate:2  },
        {defTypeId:8 , atkTypeId:12, damageRate:0.5},
        {defTypeId:8 , atkTypeId:13, damageRate:1  },
        {defTypeId:8 , atkTypeId:14, damageRate:1  },
        {defTypeId:8 , atkTypeId:15, damageRate:1  },
        {defTypeId:8 , atkTypeId:16, damageRate:1  },
        {defTypeId:8 , atkTypeId:17, damageRate:1  },
        {defTypeId:8 , atkTypeId:18, damageRate:0.5},
        {defTypeId:9 , atkTypeId:1 , damageRate:1  },
        {defTypeId:9 , atkTypeId:2 , damageRate:1  },
        {defTypeId:9 , atkTypeId:3 , damageRate:2  },
        {defTypeId:9 , atkTypeId:4 , damageRate:0  },
        {defTypeId:9 , atkTypeId:5 , damageRate:2  },
        {defTypeId:9 , atkTypeId:6 , damageRate:2  },
        {defTypeId:9 , atkTypeId:7 , damageRate:1  },
        {defTypeId:9 , atkTypeId:8 , damageRate:0.5},
        {defTypeId:9 , atkTypeId:9 , damageRate:1  },
        {defTypeId:9 , atkTypeId:10, damageRate:1  },
        {defTypeId:9 , atkTypeId:11, damageRate:1  },
        {defTypeId:9 , atkTypeId:12, damageRate:1  },
        {defTypeId:9 , atkTypeId:13, damageRate:0.5},
        {defTypeId:9 , atkTypeId:14, damageRate:1  },
        {defTypeId:9 , atkTypeId:15, damageRate:1  },
        {defTypeId:9 , atkTypeId:16, damageRate:1  },
        {defTypeId:9 , atkTypeId:17, damageRate:1  },
        {defTypeId:9 , atkTypeId:18, damageRate:1  },
        {defTypeId:10, atkTypeId:1 , damageRate:1  },
        {defTypeId:10, atkTypeId:2 , damageRate:1  },
        {defTypeId:10, atkTypeId:3 , damageRate:1  },
        {defTypeId:10, atkTypeId:4 , damageRate:2  },
        {defTypeId:10, atkTypeId:5 , damageRate:0.5},
        {defTypeId:10, atkTypeId:6 , damageRate:2  },
        {defTypeId:10, atkTypeId:7 , damageRate:0.5},
        {defTypeId:10, atkTypeId:8 , damageRate:1  },
        {defTypeId:10, atkTypeId:9 , damageRate:0  },
        {defTypeId:10, atkTypeId:10, damageRate:1  },
        {defTypeId:10, atkTypeId:11, damageRate:1  },
        {defTypeId:10, atkTypeId:12, damageRate:0.5},
        {defTypeId:10, atkTypeId:13, damageRate:2  },
        {defTypeId:10, atkTypeId:14, damageRate:1  },
        {defTypeId:10, atkTypeId:15, damageRate:1  },
        {defTypeId:10, atkTypeId:16, damageRate:1  },
        {defTypeId:10, atkTypeId:17, damageRate:1  },
        {defTypeId:10, atkTypeId:18, damageRate:1  },
        {defTypeId:11, atkTypeId:1 , damageRate:1  },
        {defTypeId:11, atkTypeId:2 , damageRate:1  },
        {defTypeId:11, atkTypeId:3 , damageRate:1  },
        {defTypeId:11, atkTypeId:4 , damageRate:1  },
        {defTypeId:11, atkTypeId:5 , damageRate:1  },
        {defTypeId:11, atkTypeId:6 , damageRate:1  },
        {defTypeId:11, atkTypeId:7 , damageRate:0.5},
        {defTypeId:11, atkTypeId:8 , damageRate:1  },
        {defTypeId:11, atkTypeId:9 , damageRate:1  },
        {defTypeId:11, atkTypeId:10, damageRate:1  },
        {defTypeId:11, atkTypeId:11, damageRate:0.5},
        {defTypeId:11, atkTypeId:12, damageRate:2  },
        {defTypeId:11, atkTypeId:13, damageRate:1  },
        {defTypeId:11, atkTypeId:14, damageRate:2  },
        {defTypeId:11, atkTypeId:15, damageRate:1  },
        {defTypeId:11, atkTypeId:16, damageRate:2  },
        {defTypeId:11, atkTypeId:17, damageRate:1  },
        {defTypeId:11, atkTypeId:18, damageRate:1  },
        {defTypeId:12, atkTypeId:1 , damageRate:1  },
        {defTypeId:12, atkTypeId:2 , damageRate:2  },
        {defTypeId:12, atkTypeId:3 , damageRate:1  },
        {defTypeId:12, atkTypeId:4 , damageRate:1  },
        {defTypeId:12, atkTypeId:5 , damageRate:0.5},
        {defTypeId:12, atkTypeId:6 , damageRate:1  },
        {defTypeId:12, atkTypeId:7 , damageRate:0.5},
        {defTypeId:12, atkTypeId:8 , damageRate:1  },
        {defTypeId:12, atkTypeId:9 , damageRate:0.5},
        {defTypeId:12, atkTypeId:10, damageRate:2  },
        {defTypeId:12, atkTypeId:11, damageRate:1  },
        {defTypeId:12, atkTypeId:12, damageRate:1  },
        {defTypeId:12, atkTypeId:13, damageRate:2  },
        {defTypeId:12, atkTypeId:14, damageRate:1  },
        {defTypeId:12, atkTypeId:15, damageRate:1  },
        {defTypeId:12, atkTypeId:16, damageRate:1  },
        {defTypeId:12, atkTypeId:17, damageRate:1  },
        {defTypeId:12, atkTypeId:18, damageRate:1  },
        {defTypeId:13, atkTypeId:1 , damageRate:0.5},
        {defTypeId:13, atkTypeId:2 , damageRate:0.5},
        {defTypeId:13, atkTypeId:3 , damageRate:2  },
        {defTypeId:13, atkTypeId:4 , damageRate:1  },
        {defTypeId:13, atkTypeId:5 , damageRate:2  },
        {defTypeId:13, atkTypeId:6 , damageRate:1  },
        {defTypeId:13, atkTypeId:7 , damageRate:2  },
        {defTypeId:13, atkTypeId:8 , damageRate:0.5},
        {defTypeId:13, atkTypeId:9 , damageRate:2  },
        {defTypeId:13, atkTypeId:10, damageRate:0.5},
        {defTypeId:13, atkTypeId:11, damageRate:1  },
        {defTypeId:13, atkTypeId:12, damageRate:1  },
        {defTypeId:13, atkTypeId:13, damageRate:1  },
        {defTypeId:13, atkTypeId:14, damageRate:1  },
        {defTypeId:13, atkTypeId:15, damageRate:1  },
        {defTypeId:13, atkTypeId:16, damageRate:1  },
        {defTypeId:13, atkTypeId:17, damageRate:2  },
        {defTypeId:13, atkTypeId:18, damageRate:1  },
        {defTypeId:14, atkTypeId:1 , damageRate:0  },
        {defTypeId:14, atkTypeId:2 , damageRate:1  },
        {defTypeId:14, atkTypeId:3 , damageRate:1  },
        {defTypeId:14, atkTypeId:4 , damageRate:1  },
        {defTypeId:14, atkTypeId:5 , damageRate:1  },
        {defTypeId:14, atkTypeId:6 , damageRate:1  },
        {defTypeId:14, atkTypeId:7 , damageRate:0  },
        {defTypeId:14, atkTypeId:8 , damageRate:0.5},
        {defTypeId:14, atkTypeId:9 , damageRate:1  },
        {defTypeId:14, atkTypeId:10, damageRate:1  },
        {defTypeId:14, atkTypeId:11, damageRate:1  },
        {defTypeId:14, atkTypeId:12, damageRate:0.5},
        {defTypeId:14, atkTypeId:13, damageRate:1  },
        {defTypeId:14, atkTypeId:14, damageRate:2  },
        {defTypeId:14, atkTypeId:15, damageRate:1  },
        {defTypeId:14, atkTypeId:16, damageRate:2  },
        {defTypeId:14, atkTypeId:17, damageRate:1  },
        {defTypeId:14, atkTypeId:18, damageRate:1  },
        {defTypeId:15, atkTypeId:1 , damageRate:1  },
        {defTypeId:15, atkTypeId:2 , damageRate:0.5},
        {defTypeId:15, atkTypeId:3 , damageRate:0.5},
        {defTypeId:15, atkTypeId:4 , damageRate:0.5},
        {defTypeId:15, atkTypeId:5 , damageRate:0.5},
        {defTypeId:15, atkTypeId:6 , damageRate:2  },
        {defTypeId:15, atkTypeId:7 , damageRate:1  },
        {defTypeId:15, atkTypeId:8 , damageRate:1  },
        {defTypeId:15, atkTypeId:9 , damageRate:1  },
        {defTypeId:15, atkTypeId:10, damageRate:1  },
        {defTypeId:15, atkTypeId:11, damageRate:1  },
        {defTypeId:15, atkTypeId:12, damageRate:1  },
        {defTypeId:15, atkTypeId:13, damageRate:1  },
        {defTypeId:15, atkTypeId:14, damageRate:1  },
        {defTypeId:15, atkTypeId:15, damageRate:2  },
        {defTypeId:15, atkTypeId:16, damageRate:1  },
        {defTypeId:15, atkTypeId:17, damageRate:1  },
        {defTypeId:15, atkTypeId:18, damageRate:2  },
        {defTypeId:16, atkTypeId:1 , damageRate:1  },
        {defTypeId:16, atkTypeId:2 , damageRate:1  },
        {defTypeId:16, atkTypeId:3 , damageRate:1  },
        {defTypeId:16, atkTypeId:4 , damageRate:1  },
        {defTypeId:16, atkTypeId:5 , damageRate:1  },
        {defTypeId:16, atkTypeId:6 , damageRate:1  },
        {defTypeId:16, atkTypeId:7 , damageRate:2  },
        {defTypeId:16, atkTypeId:8 , damageRate:1  },
        {defTypeId:16, atkTypeId:9 , damageRate:1  },
        {defTypeId:16, atkTypeId:10, damageRate:1  },
        {defTypeId:16, atkTypeId:11, damageRate:0  },
        {defTypeId:16, atkTypeId:12, damageRate:2  },
        {defTypeId:16, atkTypeId:13, damageRate:1  },
        {defTypeId:16, atkTypeId:14, damageRate:0.5},
        {defTypeId:16, atkTypeId:15, damageRate:1  },
        {defTypeId:16, atkTypeId:16, damageRate:0.5},
        {defTypeId:16, atkTypeId:17, damageRate:1  },
        {defTypeId:16, atkTypeId:18, damageRate:2  },
        {defTypeId:17, atkTypeId:1 , damageRate:0.5},
        {defTypeId:17, atkTypeId:2 , damageRate:2  },
        {defTypeId:17, atkTypeId:3 , damageRate:1  },
        {defTypeId:17, atkTypeId:4 , damageRate:1  },
        {defTypeId:17, atkTypeId:5 , damageRate:0.5},
        {defTypeId:17, atkTypeId:6 , damageRate:0.5},
        {defTypeId:17, atkTypeId:7 , damageRate:2  },
        {defTypeId:17, atkTypeId:8 , damageRate:0  },
        {defTypeId:17, atkTypeId:9 , damageRate:2  },
        {defTypeId:17, atkTypeId:10, damageRate:0.5},
        {defTypeId:17, atkTypeId:11, damageRate:0.5},
        {defTypeId:17, atkTypeId:12, damageRate:0.5},
        {defTypeId:17, atkTypeId:13, damageRate:0.5},
        {defTypeId:17, atkTypeId:14, damageRate:1  },
        {defTypeId:17, atkTypeId:15, damageRate:0.5},
        {defTypeId:17, atkTypeId:16, damageRate:1  },
        {defTypeId:17, atkTypeId:17, damageRate:0.5},
        {defTypeId:17, atkTypeId:18, damageRate:0.5},
        {defTypeId:18, atkTypeId:1 , damageRate:1  },
        {defTypeId:18, atkTypeId:2 , damageRate:1  },
        {defTypeId:18, atkTypeId:3 , damageRate:1  },
        {defTypeId:18, atkTypeId:4 , damageRate:1  },
        {defTypeId:18, atkTypeId:5 , damageRate:1  },
        {defTypeId:18, atkTypeId:6 , damageRate:1  },
        {defTypeId:18, atkTypeId:7 , damageRate:0.5},
        {defTypeId:18, atkTypeId:8 , damageRate:2  },
        {defTypeId:18, atkTypeId:9 , damageRate:1  },
        {defTypeId:18, atkTypeId:10, damageRate:1  },
        {defTypeId:18, atkTypeId:11, damageRate:1  },
        {defTypeId:18, atkTypeId:12, damageRate:0.5},
        {defTypeId:18, atkTypeId:13, damageRate:1  },
        {defTypeId:18, atkTypeId:14, damageRate:1  },
        {defTypeId:18, atkTypeId:15, damageRate:0  },
        {defTypeId:18, atkTypeId:16, damageRate:0.5},
        {defTypeId:18, atkTypeId:17, damageRate:2  },
        {defTypeId:18, atkTypeId:18, damageRate:1  }]
};
